### ISSUE TITLE
How to change the max player via the plugin

### ISSUE THREAD

**Issue by Endermanbugzjfc** [minijaham/UnlimitedSlots#2]
> Server will still kick players if there were more than max player count specified in server.properties
- By [GamakCZ](https://forums.pmmp.io/threads/set-max-players-inside-a-plugin.9424/#post-70628)

Please don't dream to have unlimited player slots in the free server hosting platforms :)

**Comment by minijaham** [comment]
RIP .-. I should've added that in readme. And what do you mean by free server hosting platforms...

**Comment by Endermanbugzjfc** [comment]
> RIP .-. I should've added that in readme. And what do you mean by free server hosting platforms...

🤔 Weird

**Comment by Endermanbugzjfc** [comment]
> RIP .-. I should've added that in readme. And what do you mean by free server hosting platforms...

Such as mineservers.io, it limits the max player amount to 20, so I just asked how da faq u can change the player max amount via a plugin lmao ([Check this](https://forums.pmmp.io/threads/set-max-players-inside-a-plugin.9424/#post-70628))

![image](https://user-images.githubusercontent.com/53002741/81478659-60aa4800-9251-11ea-8540-a7b0baea7912.png)

**Comment by minijaham** [comment]
I believe if you are using a server hoster, You cannot change it via the plugin itself.

**Comment by minijaham** [comment]
Oh wait lol I think I misunderstood what you were trying to say

**Comment by minijaham** [comment]
@Endermanbugzjfc, I haven't tried it so I don't know if it would work or not on free hosters .-. 
You can try it yourself and see if it works lol
It would be the coolest thing for people who are using free hosters if it works

**Comment by Endermanbugzjfc** [comment]
hey my title .-.

**Comment by minijaham** [comment]
.-.
